### ISSUE TITLE
Thanks and a small request

### ISSUE THREAD

**Issue by NikiRitt** [acdh-oeaw/ecce#5]
Dear all,
just wanted to say thank you for having finished the online version of the manual. One thing would really be cool, though, namely to set up the possibility of downloading the token result lists also in excel format, not only in *_cvs. Since the fields also contain commas, excel cannot deal with the *.cvs files.
Thank you soo much, and be in touch,
Niki

**Comment by csae8092** [comment]
Dear @NikiRitt 
It is now possible to download the [total results of the tokens](https://ecce.acdh.oeaw.ac.at/browsing/tokens/) but only as csv because providing an excel file format consume far too much memory and takes too much time. 
I know, Excel has quite some issues with reading .csv files. Thats why we are using [Libre Office](https://www.libreoffice.org/) 
But we will add a selection field where users can decide which delimiter the csv should use. Usually "us"-Excel can deal with .csvs using "," while "german"-Excel can only work with ";"...

**Comment by csae8092** [comment]
@zxenia 
can you maybe make some nice dropdown button or so....
